### ISSUE TITLE
引入import 建议

### ISSUE THREAD

**Issue by hange1223** [muyao1987/leaflet-tileLayer-baidugaode#3]
未采用，不知道头部引入了哪些文件，报错leaflet-src.js:3931 Uncaught TypeError: Cannot read property 'latLngToPoint' of undefined

**Comment by muyao1987** [comment]
参考代码：基于proj4，需要先引入这个

<script src="https://cdn.bootcss.com/proj4js/2.4.3/proj4.js"></script>
<script src="https://cdn.bootcss.com/proj4leaflet/1.0.1/proj4leaflet.min.js"></script>

再引入插件
<script src="../src/tileLayer.baidu.js"></script>
